### ISSUE TITLE
Change the power button behaviour

### ISSUE THREAD

**Issue by maxliem** [rpetrich/libactivator#35] opened 2010-04-05 19:49 UTC
Hi,

The app is great but here is why I don't like the behaviour of the Power/sleep button with Activator. First without Activator, if you call someone with a bluetooth headset and you want to turn off the screen, you need to press twice on the power button. But with Activator, after pressing twice the phone is not sleeping and the screen remains ON. I need to push one more time on the button.
Is there any way to not mess the phone behaviour when you push twice the sleep button ?
Perhaps by implemanting a ON/OFF function for this action.

Thanks

**Comment by rpetrich** [comment] 2010-04-11 09:57
When an action assigned to double-tap on the sleep button, it will ensure the device is awake before sending it. This is the intended behaviour.

If you don't want something assigned to that gesture, unassign it in Settings.app

**Closed as completed by rpetrich** 2010-04-11 09:57 UTC

**Comment by maxliem** [comment] 2010-04-11 14:08
Actually, I've already set the gesture to nothing and it still change the behaviour of the phone.
