### ISSUE TITLE
Double click home between locking.

### ISSUE THREAD

**Issue by ghost** [rpetrich/libactivator#71] opened 2010-08-04 16:10 UTC
If you lock your phone and attempt to unlock it right after by pressing the top button it flashes then loads.

**Comment by ghost** [comment] 2010-08-04 16:12
http://forums.macrumors.com/showthread.php?t=984558
Where forum discovered issue.

**Comment by rpetrich** [comment] 2010-08-19 05:17
Duplicate of Issue 70.

**Closed as completed by rpetrich** 2010-08-19 05:17 UTC
