### ISSUE TITLE
Unexpected behavior: event.handled = YES on hook of -[LAActivator sendEventToListener:] 

### ISSUE THREAD

**Issue by robertorfischer** [rpetrich/libactivator#41] opened 2010-04-23 19:19 UTC
On 1.2, hooking on -[LAActivator sendEventToListener:] and setting event.handled = YES would result in that event not triggering any actions in the LAActivator chain. This was suggested by rpetrich so I could use home button (single tap, double tap and hold) to control my plugin. It worked as expected: actions wouldn't be sent to anyone in the chain, so nothing would happen outside of my plugin.

Now, on 1.3, this same procedure still delivers the event to the system action. One thing to note is that the "home button on springboard" event won't be created after an unhandled "home button" event when springboard is visible is fired. This happens, as expected, when event.handled = NO.

**Comment by rpetrich** [comment] 2010-04-23 21:45
For 1.3, the single press home action was changed to always return to home screen so that a user could never become "stuck inside an application." The `sendDeactivateEventToListeners:` is called to deactivate via the menu button and inhibits the original system action (though I reserve the right to change this as well).

The `"libactivator.menu.press.at-springboard"` event no longer exists as there was overwhelming support for replacing it with `"libactivator.menu.press.single"`

Also, I am still opposed to this level of hooking; I am willing to satisfy additional API requests if they make sense (perhaps around making an event temporarily become a deactivate event?)

**Comment by robertorfischer** [comment] 2010-04-24 00:18
I seek a way to control my plugin on the springboard the same way as on the lock screen with a SBAwayViewPluginController. I don't believe regulating such things as that home button event is reasonable. If an API that's supposed to centralize triggers restricts usage, you get the exact opposite effect. You shouldn't worry about policing how people use your plugin.

One thing that's missing in Activator is some kind of stack of active plugins. This way, its top would be the first responder in the events chain. No hacks or exceptions needed
to grab events other than "deactivation" (which is not always the way home button might be used) or triggers not associated with that plugin.

**Comment by rpetrich** [comment] 2010-04-28 20:43
If you require an action to be reassignable and accessed at any time, you should register it with Activator. If you require an action to be performed only when your view is active, you should hook whatever methods you need.  I don't police how developers use it, but I won't support or encourage uses that are counter to its intended purpose.

Activator was designed to return control over gestures to users, not simply to make things easier for developers (though it does do that in most cases). I oppose subverting the settings the user has setup; I won't be implementing an "event stack" since it does just that.

**Closed as completed by rpetrich** 2010-04-28 20:43 UTC
